name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Runs only when push to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t alantomanu/shopease:latest .

      - name: Push image to Docker Hub
        run: docker push alantomanu/shopease:latest
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"

      - name: Redeploy Docker image to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: shop-ease
          service-name: shop-ease
          docker: alantomanu/shopease:latest
          service-instance-type: free
          service-regions: fra
          service-ports: "8000:http"
          service-routes: "/:8000"
